# Generated by Django 3.0 on 2022-07-01 13:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_tecnica_hispatec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(max_length=600),
        ),
        migrations.CreateModel(
            name='Book_lending',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lend_start_date', models.DateTimeField()),
                ('lend_expected_finish_date', models.DateTimeField()),
                ('lend_real_finish_date', models.DateTimeField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba_tecnica_hispatec.Book')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba_tecnica_hispatec.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey( blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba_tecnica_hispatec.Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba_tecnica_hispatec.Category'),
            preserve_default=False,
        ),
    ]
