# Generated by Django 3.0 on 2022-07-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_tecnica_hispatec', '0002_auto_20220701_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='book_lending',
            name='lend_expected_finish_date',
        ),
        migrations.RemoveField(
            model_name='book_lending',
            name='lend_real_finish_date',
        ),
        migrations.RemoveField(
            model_name='book_lending',
            name='lend_start_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='birth_date',
        ),
    ]
