# Generated by Django 3.0 on 2022-07-01 14:27

from django.db import migrations
from prueba_tecnica_hispatec.models import Book
from django.apps import apps as global_apps

def populate_categories(apps, schema_editor):
    categories_names =["Adventure","Sci-Fi","Tales","Sports","Comedy"]

    for category_name in categories_names:
        category_name = Book(title=category_name)
        category_name.save()

class Migration(migrations.Migration):

    dependencies = [
        ('prueba_tecnica_hispatec', '0004_auto_20220701_1424'),
    ]

    operations = [
        migrations.RunPython(populate_categories),
    ]
