# Generated by Django 3.0 on 2022-07-01 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_tecnica_hispatec', '0008_auto_20220701_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba_tecnica_hispatec.Author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba_tecnica_hispatec.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_lending',
            name='lend_expected_finish_date',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_lending',
            name='lend_real_finish_date',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_lending',
            name='lend_start_date',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
