# Generated by Django 3.0 on 2022-07-01 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_tecnica_hispatec', '0011_auto_20220701_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default='1000-01-01'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prueba_tecnica_hispatec.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prueba_tecnica_hispatec.Category'),
        ),
        migrations.AlterField(
            model_name='book_lending',
            name='lend_expected_finish_date',
            field=models.DateTimeField(default='1000-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='book_lending',
            name='lend_real_finish_date',
            field=models.DateTimeField(default='1000-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='book_lending',
            name='lend_start_date',
            field=models.DateTimeField(default='1000-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(default='1000-01-01'),
        ),
    ]
