# Generated by Django 3.0 on 2022-07-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_tecnica_hispatec', '0012_auto_20220701_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default='1000-01-01'),
        ),
    ]
