# Generated by Django 3.0 on 2022-07-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_tecnica_hispatec', '0015_auto_20220701_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_lending',
            name='lend_expected_finish_date',
            field=models.DateField(default='1000-01-01'),
        ),
        migrations.AlterField(
            model_name='book_lending',
            name='lend_real_finish_date',
            field=models.DateField(default='1000-01-01'),
        ),
        migrations.AlterField(
            model_name='book_lending',
            name='lend_start_date',
            field=models.DateField(default='1000-01-01'),
        ),
    ]
