# Generated by Django 3.0 on 2022-07-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_tecnica_hispatec', '0016_auto_20220701_2353'),
    ]

    operations = [
    ]
