# Generated by Django 3.0 on 2022-07-01 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_tecnica_hispatec', '0020_auto_20220702_0030'),
    ]

    operations = [
    ]
