# Generated by Django 3.0 on 2022-07-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_tecnica_hispatec', '0022_auto_20220702_0036'),
    ]

    operations = [
    ]
