# Generated by Django 3.0 on 2022-07-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_tecnica_hispatec', '0024_auto_20220702_0040'),
    ]

    operations = [
    ]
