# Generated by Django 3.0 on 2022-07-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_tecnica_hispatec', '0028_auto_20220702_0047'),
    ]

    operations = [
    ]
