# Generated by Django 3.0 on 2022-07-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_tecnica_hispatec', '0030_auto_20220702_1129'),
    ]

    operations = [
    ]
